<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
    <PackageReference Include="Microsoft.Orleans.Runtime" Version="10.3.0" />
    <PackageReference Include="Microsoft.Orleans.Sdk" Version="10.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShoppingApp.Abstractions\ShoppingApp.Abstractions.csproj" />
  </ItemGroup>

</Project>
