run-name: Run Integration Tests

on: [push]
jobs:
  Build_Solution:
    runs-on: [self-hosted, dotnet]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore ShoppingApp.slnx
      - name: Build_Solution
        run: dotnet build ShoppingApp.slnx --configuration Release --no-restore
      - name: Run Integration Tests
        run: dotnet run --project test/ShoppingApp.Tests
      - name: Run FSharp Integration Tests
        run: dotnet run --project test/ShoppingApp.Tests.FSharp