run-name: Publishing Solution Artifacts

on: [push]

env:
  # Staging 'sa1, sa2 sa3, ...'
  # s - staging a - advanced => sa
  nameSuffix: 'sa1'
  appNamePrefix: 'shoppingapp1'

jobs:
  Build_Solution:
    runs-on: [self-hosted, dotnet]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore ShoppingApp.sln
      - name: Build_Solution
        run: dotnet build ShoppingApp.sln --configuration Release --no-restore
      - name: Run Integration Tests
        run: > 
          dotnet test test/ShoppingApp.Tests --no-restore --verbosity normal --logger trx 
          --results-directory "IntegrationTestsResults"
      - uses: actions/upload-artifact@v3
        with:
          name: Integration Tests Results
          path: IntegrationTestsResults
      # Packing Infrastructure Artifacts Stage
      - uses: actions/upload-artifact@v3
        with:
          name: infrastructure
          path: ${{ github.workspace }}/**/deploy/azure-container-apps

##################### Provision Azure Container Registry Stage #####################
  Provision_Azure_Container_Registry:
    needs: Build_Solution
    runs-on: [self-hosted, azure-cli]
    env:
      resourceGroupName: 'rg-shopping-app-main'
      location: 'francecentral'
    outputs:
      acrName: ${{ steps.step1.outputs.acrName }}
      acrResourceGroupName: ${{ env.resourceGroupName }}
      acrUrl: ${{ steps.step1.outputs.acrUrl }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: 'infrastructure'
          path: ${{ github.workspace }}/infrastructure
      - name: Log infrastructure download
        run: ls -R
      - name: Log in with Azure
        uses: azure/login@v1
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - id: step1
        name: Create Azure Container Registry
        run: |
          az --version
          az group create --name $resourceGroupName --location $location
          ACR_CREDENTIALS=$(az deployment group create --resource-group $resourceGroupName \
            --template-file ${{ github.workspace }}/infrastructure/deploy/azure-container-apps/azure-container-registry.bicep \
            --parameters appNamePrefix=$appNamePrefix --query properties.outputs)
          # Retrieve the output values from the deployment
          ACR_NAME=$(jq --raw-output '.acrName.value' <<< $ACR_CREDENTIALS)
          ACR_URL=$(jq --raw-output '.acrUrl.value' <<< $ACR_CREDENTIALS)
          if [[ -z $ACR_URL ]]; then
            echo "Error: ACR_URL is empty"
            exit 1
          fi
          echo "Setting ACR_CREDENTIALS for output"
          echo "ACR credentials is: $ACR_NAME $ACR_URL"
          env | sort
          echo "acrName=$ACR_NAME" >> $GITHUB_OUTPUT
          echo "acrUrl=$ACR_URL" >> $GITHUB_OUTPUT
  
##################### Publishing Solution Artifacts Stage #####################
  Publishing_Solution_Artifacts:
    runs-on: [self-hosted, azure-cli]
    needs: Provision_Azure_Container_Registry
    outputs:
      semVer: ${{ steps.step1.outputs.semVer }}
    env:
      acrUrl: ${{ needs.Provision_Azure_Container_Registry.outputs.acrUrl }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: 'infrastructure'
          path: ${{ github.workspace }}/infrastructure
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.3
        with:
          versionSpec: '6.x'
          includePrerelease: true
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.0.3
        with:
          useConfigFile: true
          configFilePath: ${{ github.workspace }}/GitVersion.yml
      - name: Log in with Azure
        uses: azure/login@v1
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: 'Build and push images to Azure Container Registry'
        id: step1
        env:
          acrUrl: ${{ needs.Provision_Azure_Container_Registry.outputs.acrUrl }}
          semVer: ${{ steps.gitversion.outputs.semVer }} 
        run: |
          az acr login --name ${{ env.acrUrl }}
          docker build -t "${{ env.acrUrl }}/shoppingapp/silohost:${{ env.semVer }}" \
          -f ${{ github.workspace }}/src/ShoppingApp.SiloHost/Dockerfile . \
          --build-arg assemblyInformationalVersion=${{ steps.gitversion.outputs.informationalVersion }}
          docker push "${{ env.acrUrl }}/shoppingapp/silohost:${{ env.semVer }}"
          docker build -t "${{ env.acrUrl }}/shoppingapp/webui:${{ env.semVer }}" \
          -f ${{ github.workspace }}/src/ShoppingApp.WebUI/Dockerfile . \
          --build-arg assemblyInformationalVersion=${{ steps.gitversion.outputs.informationalVersion }}
          docker push "${{ env.acrUrl }}/shoppingapp/webui:${{ env.semVer }}"
          echo "Setting semVer for output"
          echo "semVer=${{ env.semVer }}" >> $GITHUB_OUTPUT